site:
  name: Sports Scouting Sudamérica
  site: 'https://sports-scouting.bg'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: null

# Default SEO metadata
metadata:
  title:
    default: Sports Scouting Sudamérica · Bulgaria
    template: '%s · Sports Scouting Sudamérica'
  description: "Proyecto integral para fundar una Escuela Integral de Fútbol profesional en Bulgaria que une el talento búlgaro y sudamericano para competir al máximo nivel internacional."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Sports Scouting Sudamérica · Bulgaria
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@sportsscouting'
    site: '@sportsscouting'
    cardType: summary_large_image

i18n:
  language: es
  textDirection: ltr

apps:
  blog:
    isEnabled: false
    postsPerPage: 0

    post:
      isEnabled: false
      permalink: '/%slug%'
      robots:
        index: false

    list:
      isEnabled: false
      pathname: 'blog'
      robots:
        index: false

    category:
      isEnabled: false
      pathname: 'category'
      robots:
        index: false

    tag:
      isEnabled: false
      pathname: 'tag'
      robots:
        index: false

    isRelatedPostsEnabled: false
    relatedPostsCount: 0

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
